### PR TITLE
Vs2015 rc

### PR DESCRIPTION
**Pull request by msimons1**
VS2015 RC branch should be merged into master.

### CODE REVIEW

**Comment by SteveLasker** [comment]
That's quite the list.
Great work! The salesforce connected service is flushing out most of the issues and extensibility points authors can reference.
All the polish, and my favorite, the iterative update scenario.
The countdown begins.

Sent from my Windows 8 Phone
________________________________

**Comment by dcarroll** [comment]
Is this fully pushed and committed?

On Tue, Apr 28, 2015 at 6:44 AM, Steve Lasker <notifications@github.com>
wrote:

> That's quite the list.
> Great work! The salesforce connected service is flushing out most of the
> issues and extensibility points authors can reference.
> All the polish, and my favorite, the iterative update scenario.
> The countdown begins.
>
> Sent from my Windows 8 Phone
> ________________________________
> From: msimons1<mailto:notifications@github.com>
> Sent: ‎4/‎28/‎2015 5:56 AM
> To: developerforce/visual-studio-tools<mailto:
> visual-studio-tools@noreply.github.com>
> Subject: [visual-studio-tools] Vs2015 rc (#4)
>
> VS2015 RC branch should be merged into master.
> You can view, comment on, or merge this pull request online at:
>
> https://github.com/developerforce/visual-studio-tools/pull/4
>
> -- Commit Summary --
>
> * -Removal of dependency on ConnectedServices.Framework.
> * Appveyor Dev14 image was updated to CTP, update accordingly.
> * Appveyor Dev14 image uses Dev12 to build by default, add Dev14 to path.
> * Uptaking latest core
> * Uptaking the latest core.
> * Uptake Themed Dialog style changes
> * Merge branch 'master'
> * Merge branch 'VS2015RC' of
> https://github.com/developerforce/visual-studio-tools.git
> * Merge branch 'VS2015RC' of
> https://github.com/developerforce/visual-studio-tools.git
> * Uptaking the latest core. This change brings in support for using the
> logger within the provider. The UserSettings was updated to make use of
> this rather than writing directly to the output window. I also renamed
> UserSettingsHelper to UserSettingsPersistenceHelper. This makes more sense
> now that this is no longer part of the core framework.
> * Added update support to Salesforce.
> * Completed the initial update support.
> * Update Salesforce Provider ID
> * Bug 1139182: When adding wizard pages, the Provider Author shouldn't
> have to pass in the Wizard in the constructor
> * Task 1144089 - Add the applicable project strings to existing providers.
> * Changing the Supported Project Type strings to all start with "C#",
> instead of the language being in the middle in some cases.
> * Update provider name and description
> * Update Salesforce VSIX ID in call to NuGet API
> * Fixed a regression in the update scenario caused from a recent change in
> which the Wizard property is not available in a WizardPage until the page
> is added to the wizard.
> * When creating the connected app fails because of a duplicate entry (i.e.
> name conflict), retry using a random number between 100 and 999 inclusive
> as the app name's suffix. This happens when the attempt to generate a
> unique name by reading the existing connected apps failed. It is unknown at
> this point what causes the Salesforce server to sometimes respond to a SOAP
> ReadMetadata request by returning nil for a Connected App name that
> actually exists.
> * Add a link to sign up for a Salesforce developer account
> * Use version 1.0.0 of DeveloperForce.Force
>
> -- File Changes --
>
>
> M .gitignore (1)
> D
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.Framework.XML
> (1074)
> D
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.Framework.dll
> (0)
> D
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.Framework.pdb
> (0)
> D
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.XML
> (1115)
> D
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.dll
> (0)
> D
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.pdb
> (0)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/CodeModel/ConfigurationKeyNames.cs
> (16)
> M src/Salesforce.VisualStudio.Services/ConnectedService/Constants.cs (14)
> A src/Salesforce.VisualStudio.Services/ConnectedService/DesignerData.cs
> (48)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Models/DesignTimeAuthentication.cs
> (37)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Models/RuntimeAuthentication.cs
> (6)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Models/UserSettings.cs
> (14)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Resources.Designer.cs
> (64)
> M src/Salesforce.VisualStudio.Services/ConnectedService/Resources.resx (48)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/SalesforceConnectedServiceHandler.cs
> (235)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/SalesforceConnectedServiceInstance.cs
> (26)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/SalesforceConnectedServiceProvider.cs
> (27)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/SalesforceConnectedServiceWizard.cs
> (143)
> A
> src/Salesforce.VisualStudio.Services/ConnectedService/SupportedProjectTypeStrings.Designer.cs
> (117)
> A
> src/Salesforce.VisualStudio.Services/ConnectedService/SupportedProjectTypeStrings.resx
> (138)
> A
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/CodeAnalysisHelper.cs
> (58)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/ConfigHelperExtensions.cs
> (4)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/ConnectedAppHelper.cs
> (54)
> D
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/ExceptionHelper.cs
> (24)
> A
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/GeneralUtilities.cs
> (49)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/GeneratedCodeHelper.cs
> (4)
> D
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/NamingUtilities.cs
> (25)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/RegistryHelper.cs
> (2)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/TelemetryHelper.cs
> (49)
> A
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/UserSettingsPersistenceHelper.cs
> (149)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/DesignTimeAuthenticationViewModel.cs
> (60)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/MyDomainViewModel.cs
> (18)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/ObjectPickerCategory.cs
> (8)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/ObjectPickerItem.cs
> (24)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/ObjectPickerObject.cs
> (2)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/ObjectSelectionViewModel.cs
> (78)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/RuntimeAuthenticationConfigViewModel.cs
> (35)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/RuntimeAuthenticationTypeViewModel.cs
> (9)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/SalesforceConnectedServiceWizardPage.cs
> (26)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/DesignTimeAuthenticationPage.xaml
> (13)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/DesignTimeAuthenticationPage.xaml.cs
> (13)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/EnumToBooleanConverter.cs
> (4)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/EnumToVisibilityConverter.cs
> (2)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/MyDomainControl.xaml
> (3)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/ObjectPicker.xaml
> (16)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/ObjectPicker.xaml.cs
> (12)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/ObjectSelectionPage.xaml
> (2)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/ObjectSelectionPage.xaml.cs
> (41)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/RuntimeAuthenticationConfigPage.xaml
> (18)
> M
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/RuntimeAuthenticationTypePage.xaml
> (9)
> D
> src/Salesforce.VisualStudio.Services/Packages/DeveloperForce.Force.0.6.4.nupkg
> (0)
> A
> src/Salesforce.VisualStudio.Services/Packages/DeveloperForce.Force.1.0.0.nupkg
> (0)
> A src/Salesforce.VisualStudio.Services/Packages/Microsoft.Bcl.1.1.10.nupkg
> (0)
> D src/Salesforce.VisualStudio.Services/Packages/Microsoft.Bcl.1.1.9.nupkg
> (0)
> D
> src/Salesforce.VisualStudio.Services/Packages/Microsoft.Bcl.Build.1.0.14.nupkg
> (0)
> A
> src/Salesforce.VisualStudio.Services/Packages/Microsoft.Bcl.Build.1.0.21.nupkg
> (0)
> D
> src/Salesforce.VisualStudio.Services/Packages/Microsoft.Net.Http.2.2.28.nupkg
> (0)
> A
> src/Salesforce.VisualStudio.Services/Packages/Microsoft.Net.Http.2.2.29.nupkg
> (0)
> M
> src/Salesforce.VisualStudio.Services/Salesforce.VisualStudio.Services.csproj
> (72)
> M src/Salesforce.VisualStudio.Services/app.config (5)
> M src/Salesforce.VisualStudio.Services/packages.config (11)
> M src/Salesforce.VisualStudio.Services/source.extension.vsixmanifest (6)
>
> -- Patch Links --
>
> https://github.com/developerforce/visual-studio-tools/pull/4.patch
> https://github.com/developerforce/visual-studio-tools/pull/4.diff
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/developerforce/visual-studio-tools/pull/4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/visual-studio-tools/pull/4#issuecomment-97068950>
> .
>



-- 
Thanks,
Dave

**Comment by msimons1** [comment]
Yes – I also published the build from Master with these changes to the VS Gallery.

**Comment by dcarroll** [comment]
Thanks!

On Tue, Apr 28, 2015 at 8:53 AM, msimons1 <notifications@github.com> wrote:

> Yes – I also published the build from Master with these changes to the VS
> Gallery.
>
> From: Dave Carroll [mailto:notifications@github.com]
> Sent: Tuesday, April 28, 2015 10:51 AM
> To: developerforce/visual-studio-tools
> Cc: Michael Simons (VISUAL STUDIO)
> Subject: Re: [visual-studio-tools] Vs2015 rc (#4)
>
> Is this fully pushed and committed?
>
> On Tue, Apr 28, 2015 at 6:44 AM, Steve Lasker <notifications@github.com>
> wrote:
>
> > That's quite the list.
> > Great work! The salesforce connected service is flushing out most of the
> > issues and extensibility points authors can reference.
> > All the polish, and my favorite, the iterative update scenario.
> > The countdown begins.
> >
> > Sent from my Windows 8 Phone
> > ________________________________
> > From: msimons1<mailto:notifications@github.com>
> > Sent: ‎4/‎28/‎2015 5:56 AM
> > To: developerforce/visual-studio-tools<mailto:
> > visual-studio-tools@noreply.github.com>
> > Subject: [visual-studio-tools] Vs2015 rc (#4)
> >
> > VS2015 RC branch should be merged into master.
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/developerforce/visual-studio-tools/pull/4
> >
> > -- Commit Summary --
> >
> > * -Removal of dependency on ConnectedServices.Framework.
> > * Appveyor Dev14 image was updated to CTP, update accordingly.
> > * Appveyor Dev14 image uses Dev12 to build by default, add Dev14 to
> path.
> > * Uptaking latest core
> > * Uptaking the latest core.
> > * Uptake Themed Dialog style changes
> > * Merge branch 'master'
> > * Merge branch 'VS2015RC' of
> > https://github.com/developerforce/visual-studio-tools.git
> > * Merge branch 'VS2015RC' of
> > https://github.com/developerforce/visual-studio-tools.git
> > * Uptaking the latest core. This change brings in support for using the
> > logger within the provider. The UserSettings was updated to make use of
> > this rather than writing directly to the output window. I also renamed
> > UserSettingsHelper to UserSettingsPersistenceHelper. This makes more
> sense
> > now that this is no longer part of the core framework.
> > * Added update support to Salesforce.
> > * Completed the initial update support.
> > * Update Salesforce Provider ID
> > * Bug 1139182: When adding wizard pages, the Provider Author shouldn't
> > have to pass in the Wizard in the constructor
> > * Task 1144089 - Add the applicable project strings to existing
> providers.
> > * Changing the Supported Project Type strings to all start with "C#",
> > instead of the language being in the middle in some cases.
> > * Update provider name and description
> > * Update Salesforce VSIX ID in call to NuGet API
> > * Fixed a regression in the update scenario caused from a recent change
> in
> > which the Wizard property is not available in a WizardPage until the
> page
> > is added to the wizard.
> > * When creating the connected app fails because of a duplicate entry
> (i.e.
> > name conflict), retry using a random number between 100 and 999
> inclusive
> > as the app name's suffix. This happens when the attempt to generate a
> > unique name by reading the existing connected apps failed. It is unknown
> at
> > this point what causes the Salesforce server to sometimes respond to a
> SOAP
> > ReadMetadata request by returning nil for a Connected App name that
> > actually exists.
> > * Add a link to sign up for a Salesforce developer account
> > * Use version 1.0.0 of DeveloperForce.Force
> >
> > -- File Changes --
> >
> >
> > M .gitignore (1)
> > D
> >
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.Framework.XML
>
> > (1074)
> > D
> >
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.Framework.dll
>
> > (0)
> > D
> >
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.Framework.pdb
>
> > (0)
> > D
> >
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.XML
>
> > (1115)
> > D
> >
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.dll
>
> > (0)
> > D
> >
> Externals/Microsoft.VisualStudio.ConnectedServices/Microsoft.VisualStudio.ConnectedServices.pdb
>
> > (0)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/CodeModel/ConfigurationKeyNames.cs
>
> > (16)
> > M src/Salesforce.VisualStudio.Services/ConnectedService/Constants.cs
> (14)
> > A src/Salesforce.VisualStudio.Services/ConnectedService/DesignerData.cs
> > (48)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Models/DesignTimeAuthentication.cs
>
> > (37)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Models/RuntimeAuthentication.cs
>
> > (6)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Models/UserSettings.cs
>
> > (14)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Resources.Designer.cs
> > (64)
> > M src/Salesforce.VisualStudio.Services/ConnectedService/Resources.resx
> (48)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/SalesforceConnectedServiceHandler.cs
>
> > (235)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/SalesforceConnectedServiceInstance.cs
>
> > (26)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/SalesforceConnectedServiceProvider.cs
>
> > (27)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/SalesforceConnectedServiceWizard.cs
>
> > (143)
> > A
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/SupportedProjectTypeStrings.Designer.cs
>
> > (117)
> > A
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/SupportedProjectTypeStrings.resx
>
> > (138)
> > A
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/CodeAnalysisHelper.cs
>
> > (58)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/ConfigHelperExtensions.cs
>
> > (4)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/ConnectedAppHelper.cs
>
> > (54)
> > D
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/ExceptionHelper.cs
>
> > (24)
> > A
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/GeneralUtilities.cs
>
> > (49)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/GeneratedCodeHelper.cs
>
> > (4)
> > D
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/NamingUtilities.cs
>
> > (25)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/RegistryHelper.cs
>
> > (2)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/TelemetryHelper.cs
>
> > (49)
> > A
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Utilities/UserSettingsPersistenceHelper.cs
>
> > (149)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/DesignTimeAuthenticationViewModel.cs
>
> > (60)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/MyDomainViewModel.cs
>
> > (18)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/ObjectPickerCategory.cs
>
> > (8)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/ObjectPickerItem.cs
>
> > (24)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/ObjectPickerObject.cs
>
> > (2)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/ObjectSelectionViewModel.cs
>
> > (78)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/RuntimeAuthenticationConfigViewModel.cs
>
> > (35)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/RuntimeAuthenticationTypeViewModel.cs
>
> > (9)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/SalesforceConnectedServiceWizardPage.cs
>
> > (26)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/DesignTimeAuthenticationPage.xaml
>
> > (13)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/DesignTimeAuthenticationPage.xaml.cs
>
> > (13)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/EnumToBooleanConverter.cs
>
> > (4)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/EnumToVisibilityConverter.cs
>
> > (2)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/MyDomainControl.xaml
>
> > (3)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/ObjectPicker.xaml
>
> > (16)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/ObjectPicker.xaml.cs
>
> > (12)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/ObjectSelectionPage.xaml
>
> > (2)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/ObjectSelectionPage.xaml.cs
>
> > (41)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/RuntimeAuthenticationConfigPage.xaml
>
> > (18)
> > M
> >
> src/Salesforce.VisualStudio.Services/ConnectedService/Views/RuntimeAuthenticationTypePage.xaml
>
> > (9)
> > D
> >
> src/Salesforce.VisualStudio.Services/Packages/DeveloperForce.Force.0.6.4.nupkg
>
> > (0)
> > A
> >
> src/Salesforce.VisualStudio.Services/Packages/DeveloperForce.Force.1.0.0.nupkg
>
> > (0)
> > A
> src/Salesforce.VisualStudio.Services/Packages/Microsoft.Bcl.1.1.10.nupkg
> > (0)
> > D
> src/Salesforce.VisualStudio.Services/Packages/Microsoft.Bcl.1.1.9.nupkg
> > (0)
> > D
> >
> src/Salesforce.VisualStudio.Services/Packages/Microsoft.Bcl.Build.1.0.14.nupkg
>
> > (0)
> > A
> >
> src/Salesforce.VisualStudio.Services/Packages/Microsoft.Bcl.Build.1.0.21.nupkg
>
> > (0)
> > D
> >
> src/Salesforce.VisualStudio.Services/Packages/Microsoft.Net.Http.2.2.28.nupkg
>
> > (0)
> > A
> >
> src/Salesforce.VisualStudio.Services/Packages/Microsoft.Net.Http.2.2.29.nupkg
>
> > (0)
> > M
> >
> src/Salesforce.VisualStudio.Services/Salesforce.VisualStudio.Services.csproj
>
> > (72)
> > M src/Salesforce.VisualStudio.Services/app.config (5)
> > M src/Salesforce.VisualStudio.Services/packages.config (11)
> > M src/Salesforce.VisualStudio.Services/source.extension.vsixmanifest (6)
> >
> > -- Patch Links --
> >
> > https://github.com/developerforce/visual-studio-tools/pull/4.patch
> > https://github.com/developerforce/visual-studio-tools/pull/4.diff
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/developerforce/visual-studio-tools/pull/4
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/developerforce/visual-studio-tools/pull/4#issuecomment-97068950>
>
> > .
> >
>
>
>
> --
> Thanks,
> Dave
>
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/developerforce/visual-studio-tools/pull/4#issuecomment-97112844>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/visual-studio-tools/pull/4#issuecomment-97114093>
> .
>



-- 
Thanks,
Dave

**Pull request merged**
